contributor-experience/handbook

CNAME
required to switch our url to the domain
=> added CNAME

docs/about/calendar.qmd
with weekly informal meetings in 2 time zone friendly options… starting in October 🎉
=> added calendar 

index.qmd
Closes #18. Removed coming soon.
=> Add link to community meetings on homepage.

.github/workflows/publish.yml, _quarto.yml
closes #10 
Based on [documentation](https://quarto.org/docs/publishing/github-pages.html#github-action)
=> Add publish action

docs/posts/cel-year-one/index.qmd
Here is a draft of the blog post for the first year of the grant :tada:
Feedback is encouraged!
=> Added blog post about first year of grant

CONTRIBUTE.md
=> add Contribute file

_quarto.yml, docs/guide/tools/bots.qmd
Added bots to the navigation. Edited links on the bots pages.
=> Updates to the bots content

.gitignore, _quarto.yml, docs/posts/Hello-world/index.qmd
Fixes a few internal links that were broken.
=> Fix broken internal links

blog.qmd
Closes #33 I think? Not sure if we want to customize the feed. As it is, it will create a `blog.xml` file that people can watch for any new blog content.
=> Adds RSS feed to the blog

_quarto.yml, docs/about/deployment_guide.qmd
=> Adds a deployment guide for the handbook

docs/posts/cel-cm/index.qmd
=> Add blog post on differences between CE and community management

docs/posts/dei-report/index.qmd
Hello folks,
Here is the blog post to announce our DEI insights report. Please review!
cc @tupui @marcogorelli
=> Add blog post about DEI insights report

_quarto.yml
This will fix the deployment of the DEI report blog post - see https://github.com/contributor-experience/handbook/actions/runs/4846300610/jobs/8635752988#step:4:41
=> Fix deployment

_quarto.yml, docs/about/calendar.qmd, docs/about/sponsors.qmd, docs/guide/tools/cdes.qmd, docs/guide/tools/gitpod.qmd, docs/guide/tools/introduction.qmd
Also updates documentation on the meetings and sponsors.
=> Add documentation on cloud development environments.

.github/workflows/circleci.yml
This is to allow us to have a nice preview of the rendered website on every PR :tada:
=> Add CircleCI redirect action for previewing PRs

_quarto.yml, docs/guide/comms/comm_resources.yaml, docs/guide/comms/introduction.qmd, docs/guide/comms/resources.qmd, docs/guide/comms/review_communication.qmd, styles.css
Working with May Ireland as part of our Communications Culture Lab, we have started a list of resources on communication to be shared publicly. This list is obviously not exhaustive, and it would be great to have contributions.
Another note is that I chose to do this as a [listing](https://quarto.org/docs/websites/website-listings.html), but I'm happy to reevaluate if the format is not appropriate.
=> Add resources on communication

CONTRIBUTE.md, docs/posts/dei-report/index.qmd, docs/posts/leadership/index.qmd
=> Add blog post on open source leadership

docs/guide/comms/comm_resources.yaml
=> Fix listings links

docs/posts/blog_DeaMaria/index.qmd, docs/posts/blog_NataliaMokeeva/index.qmd
=> Contributor experience blogs

.github/workflows/publish.yml
See https://github.com/quarto-dev/quarto-actions#github-actions-for-quarto
Ok I think this is finally right 😄
=> Fix version of quarto publish actions

docs/posts/blog_DeaMaria/index.qmd
The PR proposes the following changes:
1. Add a link to Dea's GitHub account to showcase better her work in open source.
2. Reformat the post to adhere to the recommended 80 characters per line.
=> Add a link to Dea's GitHub account. Reformat to 80 characters per line.

docs/posts/blog_DeaMaria/index.qmd
Add a link to Marco Gorelli’s talk for Data Umbrella that is mentioned in the blog post.
=> Add a link to Marco Gorelli's talk

CONTRIBUTE.md
Addressing https://github.com/contributor-experience/handbook/issues/96
What do you ladies think?
=> Proposing "Adding to Tools collection guideline"

_quarto.yml, docs/guide/comms/glossary.qmd
Create a glossary for OSS newcomers
Resolves https://github.com/contributor-experience/handbook/issues/73
=> Create a glossary for OSS newcomers

_quarto.yml, privacy.qmd
Adding the CEP Privacy Notice. Please note that some of the statements (e.g., use of Plausible Analytics, the project is in the US jurisdiction) are provisional.
=> Add the CEP Privacy Notice
